---
title: "Herbarium Data"
author: "Sarah Betts"
date: "2024-06-11"
output: html_document
---
# Data wrangling the Herbarium data to join with NOAA

```{r}
### Data wrangling the Herbarium data to get it where it needs to be to be joined with NOAA

library(googlesheets4)
gs4_deauth()
HerbariumData <- read_sheet("https://docs.google.com/spreadsheets/d/13vqlJXSW35_sx9veANUHr0jn4caxJzPPwRhRyDKLGFo/edit#gid=0")

```


```{r}
#Data wrangling
library(tidyverse)
library(car)

HerbariumData_test <-
HerbariumData %>%
  mutate(Phenophase = as.factor(Phenophase),
         collection_date = as.Date(paste(Year, Month, Day, sep = "-")),
         Day_of_Year = yday(collection_date), #julian date
         Latitude = as.numeric(Latitude)) %>%
  mutate(Elevation_in_Meters = map_dbl(Elevation_in_Meters, ~ ifelse(is.null(.x), NA, as.numeric(.x))))



names(HerbariumData_test)[3]<- "Phenophase_detail"
names(HerbariumData_test)[1]<- "Observation_ID"


HerbariumData_fl <-
  HerbariumData_test %>%
  filter(Phenophase == "fl") 

#create a Phenophase_Status variable for open flowers (to use with Surv function)
HerbariumData_fl <- HerbariumData_fl %>%
  mutate(Phenophase_Status = ifelse(Phenophase_detail %in% "fl", 0, 1))

```



```{r}
#adding elevation information 
library(elevatr)
library(sf)

HerbariumData_fl <- HerbariumData_fl %>% drop_na(Longitude, Latitude)

long_lat_df <- HerbariumData_fl[c(14,13)]%>%
  rename(x = Longitude , y = Latitude) %>%
  mutate(names = HerbariumData_fl$Observation_ID)
long_lat_df <- as.data.frame(long_lat_df)

# Define CRS for WGS84 lat/long
ll_prj <- "+proj=longlat +datum=WGS84 +no_defs"

#takes some time to run
elevation_df <- get_elev_point(locations = long_lat_df, prj = ll_prj)

#check that the length is equal to the length of HerbariumData_fl
nrow(HerbariumData_fl) == nrow(elevation_df)

#add elevation to Elevation_in_Meters only where there are NA (this will not overwrite the original elevation)
HerbariumData_fl <- HerbariumData_fl %>%
  left_join(select(elevation_df, names, elevation), by = c("Observation_ID" = "names")) %>%  
  mutate(Elevation_in_Meters = ifelse(is.na(Elevation_in_Meters), elevation, Elevation_in_Meters)) %>%  
  select(-elevation)

#check how many nas there are. If there are NAs itmost likely means it is located not in America, so these are ones we need to find manually most likely
HerbariumData_fl$Observation_ID[which(is.na(HerbariumData_fl$Elevation_in_Meters))]
```

```{r}
#standardize variables for analysis 
HerbariumData_fl$Year <- as.numeric(HerbariumData_fl$Year)
HerbariumData_fl$Year_s <- HerbariumData_fl$Year-(min(HerbariumData_fl$Year, na.rm=T)+1)
HerbariumData_fl$Elevation_s <- scale(HerbariumData_fl$Elevation_in_Meters)
```


```{r}
#Wrangling to collect met data in NOAA_mat_data.r
#create a subset of HerbariumData that does not have na
#find the indices for the rows with missing values 
missing_rows <- which(is.na(HerbariumData$Year) | is.na(HerbariumData$Latitude) | is.na(HerbariumData$Longitude))
#make new dataframe with the filtered out rows with missing values
HerbariumData_nona <- HerbariumData[-missing_rows, ]
```


