---
title: "Herbarium Data"
author: "Sarah Betts"
date: "2024-06-11"
output: html_document
---

```{r}
# #upload herbarium data
# library(readr)
# HerbariumData <- read_csv("HerbariumData.csv")

library(googlesheets4)
gs4_deauth()
HerbariumData <- read_sheet("https://docs.google.com/spreadsheets/d/13vqlJXSW35_sx9veANUHr0jn4caxJzPPwRhRyDKLGFo/edit#gid=0")

```


```{r}
#Run regression (controlling for lat, long, and flowering state)
library(tidyverse)
library(car)


HerbariumData_test <-
HerbariumData %>%
  mutate(Phenophase = as.factor(Phenophase),
         collection_date = as.Date(paste(Year, Month, Day, sep = "-")),
         julian_date = yday(collection_date),
         Latitude = as.numeric(Latitude))

names(HerbariumData_test)[3]<- "Phenophase_detail"

HerbariumData_fl <-
  HerbariumData_test %>%
  filter(Phenophase == "fl")

#run linear regression
model_fl <- lm(julian_date ~ Phenophase_detail + Latitude + Longitude + Year, data = HerbariumData_fl)
Anova(model_fl)

```

```{r}
#mean julian date by phenophase detail and year
mean_julian_data <- 
  HerbariumData_fl%>%
  mutate(Phenophase_detail = as.factor(Phenophase_detail))%>%
  filter(!is.na(julian_date))%>% #get rid of NA values for julian date
  group_by(Year, Phenophase_detail)%>%
  summarize(avg_julian = mean(julian_date, na.rm = TRUE), .groups = 'drop')

ggplot(mean_julian_data, aes(x = Year, y = avg_julian)) +
  #geom_line()+
  geom_smooth(method="lm")+
  geom_point() +
  labs(title = "Mean Julian Date by Phenophase Detail and Year",
       x = "Year",
       y = "Mean Julian Date",
       color = "Phenophase Detail")
 
ggplot(mean_julian_data, aes(x = Year, y = avg_julian, color = Phenophase_detail)) +
  #geom_line() +
  geom_point(size=1)+
  labs(title = "Mean Julian Date by Phenophase Detail and Year",
       x = "Year",
       y = "Mean Julian Date",
       color = "Phenophase Detail")+
      facet_wrap(~ Phenophase_detail, scales = "free_y") 

```



